better tests

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -1,4 +1,4 @@
-CFLAGS = -Wall
+CFLAGS = -Wall -g
 LDFLAGS = -lpthread -lrt
 CC = gcc
 SOURCES = $(wildcard *.c)
@@ -7,14 +7,23 @@ DEPS = $(patsubst %.c,%.d,$(SOURCES))
 
 all: $(BINARIES)
 
-semtest2:
-	$(CC) $(CFLAGS) $(LDFLAGS) -I ../src ../src/ui_ipc.o semtest2.c -o semtest2
-
 %: %.c
 	$(CC) $(CFLAGS) $(LDFLAGS) $< -o $(patsubst %.c,%,$<)
 
 clean:
 	rm -f $(DEPS)
 	rm -f $(BINARIES)
+
+run: all
+	@echo "* running tests"
+	for test in $(patsubst %.c,%,$(SOURCES)); do \
+		echo -n "* running $${test}"; \
+		./$${test} >/dev/null; \
+		if [ $$? -ne 0 ]; then \
+			echo " FAILED!"; \
+		else \
+			echo " OK!"; \
+		fi; \
+	done
 
 .PHONY: all install clean
